rhbase_firewall_allow_services:
  - dns

dns_nameservers: 
  - "DNS1=172.16.0.40"

bind_zone_domains:
  - name: green.local
    networks:
      - "172.16.0"
bind_listen_ipv4: ['any']
bind_allow_query: ['any']
bind_zone_master_server_ip: "172.16.0.4"

