---
rhbase_firewall_allow_services:
  - http
  - https

dns_nameservers: 
  - "DNS1=172.16.0.40"

httpd_status_enable: true

wordpress_database: 'wp_mike1'
wordpress_user: 'mike1'
wordpress_password: 'mike1'
wordpress_database_host: '172.16.0.37'
wordpress_automatic_updates: true
