# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7.5"
  config.vm.network "private_network", ip: "10.0.0.2"
#  config.vm.provision "shell", path: "./provision/pxeserver.sh"
  config.vm.hostname = "Papa1"
  config.vm.provider :virtualbox do |vb|
            vb.name = "Papa1"
  end



  config.vm.provision "ansible" do |ansible|
   ansible.playbook = "provision/playbook.yml"
  end 
end
